//! WIT/component-model host trait implementations.
//!
//! Implements the generated host traits from `crate::plugin_abi::wit_abi`
//! (phira-host, phira-query, phira-room-mgmt, etc.) so WASM plugins
//! loaded via the component model can use them instead of the JSON bridge.
//!
//! # Dual-ABI Support
//! During migration, both the JSON bridge (abi-json-v1) and the WIT
//! component model (abi-wit-v2) coexist.  Plugins are loaded via the
//! component API if they expose a component; otherwise fall back to the
//! JSON module bridge.

use std::sync::Arc;

use crate::server::PlusServerState;

/// Wraps server state to implement the generated WIT host traits.
///
/// One instance is created per plugin instance and registered with the
/// wasmtime `Linker`.
pub struct WitPluginHost {
    #[allow(dead_code)]
    state: Arc<PlusServerState>,
    plugin_name: String,
    #[allow(dead_code)]
    started: std::time::Instant,
}

impl WitPluginHost {
    pub fn new(state: Arc<PlusServerState>, plugin_name: String) -> Self {
        Self {
            state,
            plugin_name,
            started: std::time::Instant::now(),
        }
    }
}

// ── phira-host implementation ──
//
// These are the core host functions available to all WASM plugins.
// The actual trait binding is generated by bindgen! in plugin_abi.rs
// and will be connected here once the generated trait is stabilized.

impl WitPluginHost {
    /// Log a message from the plugin.
    pub fn log(&self, level: &str, message: &str) {
        match level {
            "error" => tracing::error!("[plugin:{}] {message}", self.plugin_name),
            "warn" => tracing::warn!("[plugin:{}] {message}", self.plugin_name),
            "info" => tracing::info!("[plugin:{}] {message}", self.plugin_name),
            "debug" => tracing::debug!("[plugin:{}] {message}", self.plugin_name),
            "trace" => tracing::trace!("[plugin:{}] {message}", self.plugin_name),
            _ => tracing::info!("[plugin:{}] {message}", self.plugin_name),
        }
    }

    /// Generate a UUID v4 string.
    pub fn generate_uuid(&self) -> String {
        uuid::Uuid::new_v4().to_string()
    }

    /// Get current timestamp in milliseconds.
    pub fn current_time_ms(&self) -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_millis() as u64)
            .unwrap_or(0)
    }
}

/// Result type used by WIT host functions.
pub type ApiResult = Result<crate::plugin_abi::wit_abi::JsonValue, String>;

/// Convert a serde_json::Value to a wit_abi::JsonValue.
pub fn to_wit_json(value: &serde_json::Value) -> crate::plugin_abi::wit_abi::JsonValue {
    use crate::plugin_abi::wit_abi::JsonValue;
    match value {
        serde_json::Value::Null => JsonValue::Null,
        serde_json::Value::Bool(b) => JsonValue::Flag(*b),
        serde_json::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                JsonValue::Integer(i)
            } else if let Some(f) = n.as_f64() {
                JsonValue::Float(f)
            } else {
                JsonValue::Text(n.to_string())
            }
        }
        serde_json::Value::String(s) => JsonValue::Text(s.clone()),
        serde_json::Value::Array(arr) => {
            JsonValue::Array(serde_json::to_string(arr).unwrap_or_default())
        }
        serde_json::Value::Object(obj) => {
            JsonValue::Object(serde_json::to_string(obj).unwrap_or_default())
        }
    }
}

/// Convert a wit_abi::JsonValue to serde_json::Value.
pub fn from_wit_json(value: &crate::plugin_abi::wit_abi::JsonValue) -> serde_json::Value {
    use crate::plugin_abi::wit_abi::JsonValue;
    match value {
        JsonValue::Null => serde_json::Value::Null,
        JsonValue::Flag(b) => serde_json::Value::Bool(*b),
        JsonValue::Integer(i) => serde_json::json!(*i),
        JsonValue::Float(f) => serde_json::json!(*f),
        JsonValue::Text(s) => serde_json::Value::String(s.clone()),
        JsonValue::Array(s) | JsonValue::Object(s) => {
            serde_json::from_str(s).unwrap_or(serde_json::Value::String(s.clone()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_uuid_format() {
        let s = uuid::Uuid::new_v4().to_string();
        assert_eq!(s.len(), 36);
        assert_eq!(s.chars().filter(|&c| c == '-').count(), 4);
    }

    #[test]
    fn test_json_conversion_roundtrip() {
        let original = serde_json::json!({
            "name": "test",
            "count": 42,
            "active": true,
            "data": null,
            "score": 3.14,
        });
        let wit = to_wit_json(&original);
        let back = from_wit_json(&wit);
        assert_eq!(original, back);
    }
}
