name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Setup System
        run: sudo apt-get update -y && sudo apt-get install -y musl-tools build-essential
        
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: rustup target add x86_64-unknown-linux-musl && cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phira-mp-plus-server
          path: target/release/x86_64-unknown-linux-musl/phira-mp-plus-server
          if-no-files-found: error
