name: PPA upload

on:
  workflow_dispatch:
    inputs:
      description:
        description: 版本说明（可选）
        type: string
        default: ""
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ppa-upload:
    runs-on: ubuntu-latest
    if: github.repository == 'HyperSynapseNetwork/Phira-mp-plus'
    steps:
      - uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
      - name: Build source package
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq devscripts dpkg-dev
          dpkg-buildpackage -S -d -nc
      - name: Upload to PPA
        run: |
          sudo apt-get install -y -qq dput
          dput ppa:fireflyf09/phira-mp-plus ../phira-mp-plus-server_*.source.changes
