//! ProtocolHack: centralized post-response compensation scheduling (PMP42 P1).
//!
//! The official Phira server's core command sequence never includes PMP
//! extension packets: `ChangeHost`/`ChangeState` corrections, Persistent Room
//! extra state, and replay simulation are all PMP-only additions. When PMP needs
//! such a correction, it must arrive **after** the official response has been
//! flushed, in a fixed order, and must never block the Room Actor.
//!
//! This module is the single place that schedules those compensation messages.
//! Each item records its reason for observability (`tracing::debug`). The delay
//! defaults to `minimum_response_latency_ms` (10ms) and can be set to 0 via
//! `compatibility.protocol_hack_delay_ms` for differential testing against the
//! official server.
//!
//! PMP44 P0-O: compensations bound to a session origin are **enqueued** into
//! that session's single per-session outbound channel (see
//! [`crate::session::OutboundItem::PostResponse`]) instead of spawning one task
//! per `schedule_post_response` call. The per-session outbound task drains the
//! queue strictly FIFO, so two batches scheduled close together can never
//! interleave — a later batch's `ChangeState` can never overtake an earlier
//! batch's `ChangeHost` (audit §19/§20).
//!
//! Invariants:
//! - Compensation never blocks the Room Actor (enqueue is non-blocking
//!   `try_send`; a full outbound queue means the client can never receive a
//!   state-complete connection — PMP45 P0-M closes that session so it
//!   reconnects and re-authenticates, and counts `compat_queue_drop`).
//! - Fixed emission order: [`PostResponseKind`] ascending (ChangeHost first).
//! - Critical compensation flush failure / per-item stall closes the origin
//!   session (PMP45 P0-M) — the transport is broken, the client must reconnect.
//! - The caller MUST invoke `schedule_post_response` only after the official
//!   response has been flushed to the socket.

use crate::server::config::PlusConfig;
use crate::session::{CommandOrigin, OutboundItem, Session, User};
use anyhow::anyhow;
use phira_mp_common::{ServerCommand, StreamSender};
use std::future::Future;
use std::sync::{Arc, Weak};
use tracing::{debug, warn};

/// Fixed emission order for PMP extension compensation messages.
///
/// Lower discriminants are emitted first. This order is part of the
/// compatibility contract — the official client expects host corrections before
/// state corrections, and state before replay simulation.
///
/// Only `ChangeState` is currently wired (join-reconnect WaitForReady
/// compensation); the remaining kinds are reserved for future compensation
/// sites and are exercised by the ordering tests, hence `allow(dead_code)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[allow(dead_code)]
pub(crate) enum PostResponseKind {
    /// Host correction (`ChangeHost(true/false)`).
    ChangeHost,
    /// Room state correction (`ChangeState` / `GameStart` / `StartPlaying`).
    ChangeState,
    /// Persistent Room extra state beyond the official snapshot.
    PersistentRoom,
    /// Replay simulation messages.
    Replay,
}

/// 补偿的目标。P0-O 重构后，会话内补偿直接携带 `CommandOrigin` + `ServerCommand`，
/// 由出站任务在持有 `StreamSender` 时直写 socket（而不是再次经 `try_send`
/// 回环进同一条队列，那会造成死锁/重复）。
#[derive(Debug)]
enum PostResponseTarget {
    /// 绑定到 [`CommandOrigin`] 的会话补偿（P0-A）。投递前校验 `is_current`，
    /// 起源被 reconnect 取代则丢弃并计入 `compat_queue_drop`。
    Origin(CommandOrigin, ServerCommand),
    /// 非会话（CLI/admin）补偿：无出站任务，由独立任务经 `User` 路由投递。
    User(Weak<User>, ServerCommand),
}

/// A single post-response compensation message.
#[derive(Debug)]
pub(crate) struct PostResponseItem {
    kind: PostResponseKind,
    /// Why this compensation is needed (observability/audit).
    reason: &'static str,
    target: PostResponseTarget,
}

impl PostResponseItem {
    /// Schedule a compensation that delivers `command` to `user`'s session.
    ///
    /// Legacy path for compensation sites that are not yet origin-bound; the
    /// current session is resolved at delivery time. All in-session callers
    /// have migrated to [`Self::to_origin`] (P0-A); retained for non-session
    /// (CLI/admin) compensation sites.
    #[allow(dead_code)]
    pub(crate) fn to_user(
        user: Weak<User>,
        kind: PostResponseKind,
        command: ServerCommand,
        reason: &'static str,
    ) -> Self {
        Self {
            kind,
            reason,
            target: PostResponseTarget::User(user, command),
        }
    }

    /// Schedule a compensation bound to the [`CommandOrigin`] of the command
    /// that produced it (P0-A). The delivery is dropped if the origin is stale
    /// — a reconnect bumped the generation — so a compensation generated by an
    /// old session can never reach the new session. The drop is observable via
    /// [`ProtocolTrace::compat_queue_drop`] (P1 gate: MUST be 0).
    ///
    /// P0-O: the item is enqueued into the origin session's outbound channel,
    /// and the per-session outbound task writes it directly to the socket once
    /// the origin is verified current.
    pub(crate) fn to_origin(
        origin: CommandOrigin,
        kind: PostResponseKind,
        command: ServerCommand,
        reason: &'static str,
    ) -> Self {
        Self {
            kind,
            reason,
            target: PostResponseTarget::Origin(origin, command),
        }
    }

    /// 排序键（固定投递顺序）。
    /// 当前由 `run_post_response_batch` 直接读取字段排序；保留此方法供
    /// 测试与未来调用点使用。
    #[allow(dead_code)]
    pub(crate) fn kind(&self) -> PostResponseKind {
        self.kind
    }

    /// 需要 flush 的临界补偿（`ChangeHost`/`ChangeState`）：客户端必须在后续
    /// 事件之前拿到该状态修正。
    fn is_critical(&self) -> bool {
        matches!(
            self.kind,
            PostResponseKind::ChangeHost | PostResponseKind::ChangeState
        )
    }

    /// 由出站任务（持有 `send_tx`）调用：目标 origin 仍 current 时直写 command
    /// 到 socket；stale 则丢弃并计入 `compat_queue_drop`。`send_tx` 为 `None`
    /// 表示非会话（CLI/admin）补偿路径——经 `User` 路由，无需 StreamSender。
    ///
    /// PMP45 P0-M: 返回 `Result`。临界补偿（`ChangeHost`/`ChangeState`）的
    /// `send_and_flush` 失败时返回 `Err`——连接已损坏，由 outbound task 关闭
    /// origin Session 让客户端重连（audit §23：此前 `let _ =` 静默吞掉 flush
    /// 错误，客户端可能停留在状态不完整的连接上）。
    pub(crate) async fn deliver_via(
        &self,
        send_tx: Option<&StreamSender<ServerCommand>>,
    ) -> Result<(), anyhow::Error> {
        debug!(kind = ?self.kind, reason = self.reason, "post-response compensation dispatch");
        match &self.target {
            PostResponseTarget::Origin(origin, command) => {
                let Some(send_tx) = send_tx else {
                    return Ok(());
                };
                if origin.is_current().await {
                    if self.is_critical() {
                        if let Err(err) = send_tx.send_and_flush(command.clone()).await {
                            // PMP45 P0-M: 关键补偿 flush 失败——返回失败给调用方，
                            // 由 outbound task 关闭 origin Session（连接已损坏，
                            // 客户端必须重连恢复权威状态）。
                            return Err(anyhow!(
                                "critical compensation flush failed: {err}"
                            ));
                        }
                    } else {
                        let _ = send_tx.send(command.clone()).await;
                    }
                    Ok(())
                } else {
                    let trace =
                        crate::official_client_compat::protocol_trace::ProtocolTrace::get();
                    trace
                        .compat_queue_drop
                        .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                    // PMP45 P1: 关键补偿（ChangeHost/ChangeState）被丢弃是状态不完整
                    // 信号——必须为 0。
                    if self.is_critical() {
                        trace
                            .critical_compat_drop
                            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                    }
                    debug!(
                        reason = self.reason,
                        "dropping stale post-response compensation"
                    );
                    Ok(())
                }
            }
            PostResponseTarget::User(user, command) => {
                if let Some(user) = user.upgrade() {
                    user.try_send(command.clone()).await;
                }
                Ok(())
            }
        }
    }
}

/// P0-O: 按固定 [`PostResponseKind`] 顺序串行投递一组补偿（同 kind 保持插入
/// 序）。`deliver` 闭包逐条执行；批次间由出站队列 FIFO 保证绝不乱序。
///
/// PMP45 P0-M: `deliver` 返回 `Result`——任一条补偿投递失败（flush 错误 /
/// 超时）即终止整批：该 Session 已损坏，后续补偿无意义。由调用方（outbound
/// task）负责关闭 origin Session。
pub(crate) async fn run_post_response_batch<D, F>(items: Vec<PostResponseItem>, mut deliver: D)
where
    D: FnMut(PostResponseItem) -> F,
    F: Future<Output = Result<(), anyhow::Error>> + Send,
{
    let mut items = items;
    items.sort_by_key(|it| it.kind);
    for item in items {
        if deliver(item).await.is_err() {
            // PMP45 P0-M: 投递失败即终止批次（连接已损坏）。
            break;
        }
    }
}

/// The configured ProtocolHack delay in milliseconds.
fn protocol_hack_delay_ms(config: &PlusConfig) -> u64 {
    config
        .compatibility
        .protocol_hack_delay_ms
        .unwrap_or(config.compatibility.minimum_response_latency_ms)
}

/// Schedule post-response compensation messages.
///
/// The items are sorted into the fixed [`PostResponseKind`] order and delivered
/// after `protocol_hack_delay_ms` (default `minimum_response_latency_ms`).
///
/// PMP44 P0-O: in-session compensations are **not** spawned per call. They are
/// grouped by target session and enqueued as a single
/// [`OutboundItem::PostResponse`] into that session's per-session outbound
/// channel. The single outbound task applies the delay and the fixed kind order,
/// and drains batches strictly FIFO — batch A fully completes before batch B, so
/// a later batch's `ChangeState` can never overtake an earlier batch's
/// `ChangeHost`. The enqueue is non-blocking (`try_send`), so the Room Actor
/// never waits on compensation work; a full outbound queue means the client can
/// never receive a state-complete connection — PMP45 P0-M closes that Session
/// (counts `compat_queue_drop`) so the client reconnects and re-authenticates
/// (audit §22).
///
/// Non-session (CLI/admin) compensations (`to_user`) have no outbound task and
/// are still delivered by a spawned task (legacy path).
pub(crate) fn schedule_post_response(config: &PlusConfig, items: Vec<PostResponseItem>) {
    if items.is_empty() {
        return;
    }
    let delay_ms = protocol_hack_delay_ms(config);
    // 按目标会话分组：同一 Session 的补偿批次经其出站队列串行投递（P0-O）。
    let mut session_groups: Vec<(Weak<Session>, Vec<PostResponseItem>)> = Vec::new();
    let mut user_items: Vec<PostResponseItem> = Vec::new();
    for item in items {
        // 解构以按值移动 target，同时保留 kind/reason 重建条目。
        let PostResponseItem {
            kind,
            reason,
            target,
        } = item;
        match target {
            PostResponseTarget::Origin(origin, command) => {
                let Some(session) = origin.session.upgrade() else {
                    // 起源会话已销毁——补偿不可达，计入 compat_queue_drop。
                    crate::official_client_compat::protocol_trace::ProtocolTrace::get()
                        .compat_queue_drop
                        .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                    debug!(
                        reason,
                        "dropping post-response compensation: origin session gone"
                    );
                    continue;
                };
                let session_weak = Arc::downgrade(&session);
                let rebuilt = PostResponseItem {
                    kind,
                    reason,
                    target: PostResponseTarget::Origin(origin, command),
                };
                match session_groups
                    .iter_mut()
                    .find(|(s, _)| Weak::ptr_eq(s, &session_weak))
                {
                    Some((_, group)) => group.push(rebuilt),
                    None => session_groups.push((session_weak, vec![rebuilt])),
                }
            }
            PostResponseTarget::User(user, command) => user_items.push(PostResponseItem {
                kind,
                reason,
                target: PostResponseTarget::User(user, command),
            }),
        }
    }
    // 每个 Session 一组：单次入队，出站任务按 FIFO 处理，批次间绝不乱序。
    for (session_weak, group) in session_groups {
        let Some(session) = session_weak.upgrade() else {
            continue;
        };
        if session
            .outbound_tx
            .try_send(OutboundItem::PostResponse {
                delay_ms,
                items: group,
            })
            .is_err()
        {
            // PMP45 P0-M: 关键补偿批次因出站队列拥塞被丢弃——已知状态不完整的
            // 连接不能继续维持。关闭该 Session，客户端重连 Authenticate 恢复
            // 权威状态（audit §22：此前仅计入 compat_queue_drop 就丢弃，关键的
            // ChangeHost/ChangeState 修正可能永久丢失）。
            crate::official_client_compat::protocol_trace::ProtocolTrace::get()
                .compat_queue_drop
                .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
            warn!(
                session = %session.id,
                "post-response compensation dropped (queue full); closing session"
            );
            session.stream.close();
            let _ = session.user.server.lost_con_tx.try_send(session.id);
            continue;
        }
    }
    // 非会话（CLI/admin）补偿：无出站任务，仍由独立任务投递（legacy）。
    if !user_items.is_empty() {
        tokio::spawn(async move {
            if delay_ms > 0 {
                tokio::time::sleep(std::time::Duration::from_millis(delay_ms)).await;
            }
            run_post_response_batch(
                user_items,
                |item| async move { item.deliver_via(None).await },
            )
            .await;
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    #[test]
    fn protocol_hack_kind_order_is_fixed() {
        // ChangeHost must precede ChangeState must precede PersistentRoom/Replay.
        assert!(PostResponseKind::ChangeHost < PostResponseKind::ChangeState);
        assert!(PostResponseKind::ChangeState < PostResponseKind::PersistentRoom);
        assert!(PostResponseKind::PersistentRoom < PostResponseKind::Replay);
    }

    #[test]
    fn delay_falls_back_to_minimum_response_latency() {
        let config = PlusConfig {
            compatibility: crate::CompatibilityConfig {
                minimum_response_latency_ms: 10,
                protocol_hack_delay_ms: None,
                ..Default::default()
            },
            ..Default::default()
        };
        assert_eq!(protocol_hack_delay_ms(&config), 10);
    }

    #[test]
    fn delay_can_be_zero_for_differential_tests() {
        let config = PlusConfig {
            compatibility: crate::CompatibilityConfig {
                protocol_hack_delay_ms: Some(0),
                ..Default::default()
            },
            ..Default::default()
        };
        assert_eq!(protocol_hack_delay_ms(&config), 0);
    }

    #[test]
    fn delay_respects_explicit_override() {
        let config = PlusConfig {
            compatibility: crate::CompatibilityConfig {
                minimum_response_latency_ms: 10,
                protocol_hack_delay_ms: Some(25),
                ..Default::default()
            },
            ..Default::default()
        };
        assert_eq!(protocol_hack_delay_ms(&config), 25);
    }

    #[tokio::test]
    async fn empty_items_is_a_no_op() {
        let config = PlusConfig::default();
        // Should not panic and not enqueue/spawn anything.
        schedule_post_response(&config, Vec::new());
    }

    /// P0-O: 批次内按固定 kind 顺序投递（ChangeHost → ChangeState →
    /// PersistentRoom → Replay），与投递闭包是否完成无关——顺序由排序保证。
    #[tokio::test]
    async fn batch_delivers_in_fixed_kind_order() {
        let order = Arc::new(Mutex::new(Vec::new()));
        // 目标会话已销毁（Weak::new）：deliver 闭包只观察 kind，不触发真实投递。
        let mk = |kind: PostResponseKind| PostResponseItem {
            kind,
            reason: "order test",
            target: PostResponseTarget::Origin(
                CommandOrigin {
                    session: Weak::new(),
                    generation: 0,
                },
                ServerCommand::Pong,
            ),
        };
        // 反序提交；run_post_response_batch 必须重排。
        let items = vec![
            mk(PostResponseKind::Replay),
            mk(PostResponseKind::ChangeHost),
            mk(PostResponseKind::PersistentRoom),
            mk(PostResponseKind::ChangeState),
        ];
        let order_clone = Arc::clone(&order);
        run_post_response_batch(items, move |item| {
            let order = Arc::clone(&order_clone);
            async move {
                order.lock().unwrap().push(item.kind());
                Ok::<(), anyhow::Error>(())
            }
        })
        .await;

        let got = order.lock().unwrap();
        assert_eq!(got[0], PostResponseKind::ChangeHost);
        assert_eq!(got[1], PostResponseKind::ChangeState);
        assert_eq!(got[2], PostResponseKind::PersistentRoom);
        assert_eq!(got[3], PostResponseKind::Replay);
    }
}
